#!/bin/sh

set -e
mirrors=20

print_help () {
  echo "Usage: $(basename "$0") [d|r|i|h|download|rank|install]"
}

download() {
  curl 'https://archlinux.org/mirrorlist/all/https/' | sed 's/#Server/Server/' > /tmp/mirrorlist.bak
}

rank() {
  echo "Ranking $mirrors mirrors"
  { time rankmirrors -n $mirrors /tmp/mirrorlist.bak; } \
    | grep https > /tmp/mirrorlist \
    && notify-send "Finished ranking mirrors. Enter sudo password"
}

install() {
  sudo mv /tmp/mirrorlist /tmp/mirrorlist.bak /etc/pacman.d/
}

if [ $# -eq 0 ]; then
  download
  rank
  install
else
  case $1 in
    d | download) download;;
    r | rank) rank;;
    i | install | mv) install;;
    h | help | -h ) print_help;;
  esac
fi
