#!/bin/bash

set -e

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
  echo "Usage: $(basename "$0") URL [LANG]" >&2
  exit 1
fi

url="$1"
lang="$2"

if [ "$lang" = "" ]; then
  lang="$(yt-dlp 'https://www.youtube.com/watch?v=rLfzO7Sbdc4' --print subtitles_table | grep '^en' | fzf | cut -d ' ' -f1)"
fi

yt-dlp "$url" --skip-download --write-subs --sub-langs "$lang"
